export { default as Scene01 } from './01-background.js'
export { default as Scene02 } from './02-square.js'
export { default as Scene03 } from './03-colored-square.js'
export { default as Scene04 } from './04-rotating-2d.js'
export { default as Scene05 } from './05-rotating-3d.js'
export { default as Scene06 } from './06-texture.js'
export { default as Scene07 } from './07-video-texture.js'
export { default as Scene08 } from './08-light.js'
